import { MD3DarkTheme, MD3LightTheme, useTheme } from 'react-native-paper';

const customColors = {
    light: {
        primary: "#3D3749",
        surfaceTint: "#625B6F",
        onPrimary: "#FFFFFF",
        primaryContainer: "#544E61",
        onPrimaryContainer: "#C9C0D7",
        secondary: "#615D65",
        onSecondary: "#FFFFFF",
        secondaryContainer: "#E7E0EB",
        onSecondaryContainer: "#67636B",
        tertiary: "#4A333C",
        onTertiary: "#FFFFFF",
        tertiaryContainer: "#634A53",
        onTertiaryContainer: "#DCBBC6",
        error: "#BA1A1A",
        onError: "#FFFFFF",
        errorContainer: "#FFDAD6",
        onErrorContainer: "#93000A",
        background: "#FDF8FA",
        onBackground: "#1C1B1D",
        surface: "#FDF8FA",
        onSurface: "#1C1B1D",
        surfaceVariant: "#E6E1E8",
        onSurfaceVariant: "#48464C",
        outline: "#79767C",
        outlineVariant: "#CAC5CC",
        shadow: "#000000",
        scrim: "#000000",
        inverseSurface: "#313031",
        inverseOnSurface: "#F4EFF1",
        inversePrimary: "#CBC3D9",
        primaryFixed: "#E8DFF6",
        onPrimaryFixed: "#1E1929",
        primaryFixedDim: "#CBC3D9",
        onPrimaryFixedVariant: "#4A4456",
        secondaryFixed: "#E7E0EB",
        onSecondaryFixed: "#1D1A22",
        secondaryFixedDim: "#CAC4CE",
        onSecondaryFixedVariant: "#49454E",
        tertiaryFixed: "#FCDAE5",
        onTertiaryFixed: "#29161E",
        tertiaryFixedDim: "#DFBEC9",
        onTertiaryFixedVariant: "#584049",
        surfaceDim: "#DDD9DA",
        surfaceBright: "#FDF8FA",
        surfaceContainerLowest: "#FFFFFF",
        surfaceContainerLow: "#F7F2F4",
        surfaceContainer: "#F1EDEE",
        surfaceContainerHigh: "#EBE7E9",
        surfaceContainerHighest: "#E6E1E3",
        elevation: {
            level0: "transparent",
            level1: "#FFFFFF",
            level2: "#F7F2F4",
            level3: "#F1EDEE",
            level4: "#EBE7E9",
            level5: "#E6E1E3"
        },
        success: "#2E7D32",
        onSuccess: "#FFFFFF",
        successContainer: "#E8F5E9",
        onSuccessContainer: "#1B5E20",
    },
    dark: {
        primary: "#CBC3D9",
        surfaceTint: "#CBC3D9",
        onPrimary: "#332E3F",
        primaryContainer: "#544E61",
        onPrimaryContainer: "#C9C0D7",
        secondary: "#CAC4CE",
        onSecondary: "#322F37",
        secondaryContainer: "#49454E",
        onSecondaryContainer: "#B9B3BD",
        tertiary: "#DFBEC9",
        onTertiary: "#402A32",
        tertiaryContainer: "#634A53",
        onTertiaryContainer: "#DCBBC6",
        error: "#FFB4AB",
        onError: "#690005",
        errorContainer: "#93000A",
        onErrorContainer: "#FFDAD6",
        background: "#141314",
        onBackground: "#E6E1E3",
        surface: "#141314",
        onSurface: "#E6E1E3",
        surfaceVariant: "#48464C",
        onSurfaceVariant: "#CAC5CC",
        outline: "#938F96",
        outlineVariant: "#48464C",
        shadow: "#000000",
        scrim: "#000000",
        inverseSurface: "#E6E1E3",
        inverseOnSurface: "#313031",
        inversePrimary: "#625B6F",
        primaryFixed: "#E8DFF6",
        onPrimaryFixed: "#1E1929",
        primaryFixedDim: "#CBC3D9",
        onPrimaryFixedVariant: "#4A4456",
        secondaryFixed: "#E7E0EB",
        onSecondaryFixed: "#1D1A22",
        secondaryFixedDim: "#CAC4CE",
        onSecondaryFixedVariant: "#49454E",
        tertiaryFixed: "#FCDAE5",
        onTertiaryFixed: "#29161E",
        tertiaryFixedDim: "#DFBEC9",
        onTertiaryFixedVariant: "#584049",
        surfaceDim: "#141314",
        surfaceBright: "#3A393A",
        surfaceContainerLowest: "#0F0E0F",
        surfaceContainerLow: "#1C1B1D",
        surfaceContainer: "#201F21",
        surfaceContainerHigh: "#2B292B",
        surfaceContainerHighest: "#363436",
        elevation: {
            level0: "transparent",
            level1: "#0F0E0F",
            level2: "#1C1B1D",
            level3: "#201F21",
            level4: "#2B292B",
            level5: "#363436"
        },
        success: "#81C784",
        onSuccess: "#0F1F12",
        successContainer: "#1B3A1F",
        onSuccessContainer: "#A5D6A7",
    }
};

export const momThemeLight = {
    ...MD3LightTheme,
    colors: { ...MD3LightTheme.colors, ...customColors.light },
};

export const momThemeDark = {
    ...MD3DarkTheme,
    colors: { ...MD3DarkTheme.colors, ...customColors.dark },
};

// Тип выводим из одной из тем (они должны быть идентичны по структуре)
export type AppTheme = typeof momThemeLight;
export const useAppTheme = () => useTheme<AppTheme>();

/*
#555A5C
#797A9E
#95AFBA
#444054
*/